version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@angular/cdk"
    versions:
    - 11.2.6
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.7
    - 3.6.9
  - dependency-name: karma
    versions:
    - 6.3.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.5
    - 0.1102.6
  - dependency-name: karma-jasmine
    versions:
    - 4.0.1
  - dependency-name: rxjs
    versions:
    - 6.6.6
    - 6.6.7
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: "@angular/language-service"
    versions:
    - 11.2.6
    - 11.2.7
  - dependency-name: core-js
    versions:
    - 3.9.1
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.6
  - dependency-name: karma-chrome-launcher
    versions:
    - 3.1.0
  - dependency-name: protractor
    versions:
    - 7.0.0
  - dependency-name: "@angular/core"
    versions:
    - 7.2.16
  - dependency-name: "@angular/material"
    versions:
    - 11.2.5
    - 11.2.6
  - dependency-name: tslint
    versions:
    - 5.20.1
  - dependency-name: codelyzer
    versions:
    - 6.0.1
  - dependency-name: jasmine-core
    versions:
    - 3.7.1
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: karma-coverage-istanbul-reporter
    versions:
    - 3.0.3
